---

services:
  redis:
    image: redis
    container_name: spleet-redis

  rekey-server:
    image: rekey-server
    container_name: rekey-server
    links:
      - redis:redis
    ports:
      - 1337:1337
    env_file: example.env
    environment:
      REDIS_HOST: redis
      VIRTUAL_HOST: rekey.bibby.home
      VIRTUAL_PORT: 1337
      CERT_NAME: bibby.home
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/volumes/rekey:/opt/volumes/rekey
