import os

env = os.environ.get
ORIGINAL_KEY = 0

VOLUME_BASE = '/opt/volumes/rekey'
DOCKER_USER = 1000

S3_BUCKET = env('S3_BUCKET', 'spleet.bbby.org')
DATABASE_FILE = env('DATABASE_FILE', 'app.db')

YTDLP_IMAGE = env('YTDLP_IMAGE', 'thr3a/yt-dlp')
YTDLP_OUTPUT_DIR = env('YTDLP_OUTPUT_DIR', VOLUME_BASE + '/ytdlp')

SPLEETER_IMAGE = env('SPLEETER_IMAGE', 'deezer/spleeter:3.8-2stems')
SPLEETER_INPUT_DIR = env('SPLEETER_INPUT_DIR', YTDLP_OUTPUT_DIR)
SPLEETER_OUTPUT_DIR = env('SPLEETER_OUTPUT_DIR', VOLUME_BASE + '/spleets')

KEYDETECT_IMAGE = env('KEYDETECT_IMAGE', 'key-detect')
KEYDETECT_INPUT_DIR = env('KEYDETECT_INPUT_DIR', YTDLP_OUTPUT_DIR)
KEYDETECT_OUTPUT_DIR = env('KEYDETECT_OUTPUT_DIR', VOLUME_BASE + '/keydetect')

RUBBERBAND_IMAGE = env('RUBBERBAND_IMAGE', 'rubberband')
RUBBERBAND_INPUT_DIR = env('RUBBERBAND_INPUT_DIR', YTDLP_OUTPUT_DIR)
RUBBERBAND_SPLITS_DIR = env('RUBBERBAND_SPLITS_DIR', SPLEETER_OUTPUT_DIR)
RUBBERBAND_OUTPUT_DIR = env('RUBBERBAND_OUTPUT_DIR', VOLUME_BASE + '/rubberband')

REDIS_HOST = env('REDIS_HOST', 'localhost')
REDIS_KEY_SEPERATOR = ':'
